### ISSUE TITLE
ZipFoundation - Versioning 

### ISSUE THREAD

**Issue by brandonlevasseur** [weichsel/ZIPFoundation#113]
# Summary
When supporting [Semantic Versioning](https://semver.org/spec/v2.0.0.html), there are particular rules that should be followed. One of them involves changing the `MAJOR` version when incompatible (non-backwards compatible) changes are made to a project. In the case of v0.9.9, the `PATCH` was updated with potentially non-backwards compatible functionality. What this means is, any used dependency manager will now update to the latest version causing potential issues. In the case of v0.9.9, the version of Swift was updated to 5. Any projects using older versions of Swift will now be incompatible as the versions only work intertwined under very specific conditions. This should never happen when properly versioning an SDK.

# Steps to Reproduce

Integrate a Swift 4 project with the following versions allowed via dependency managers:

~> 0.9

# Expected Results

The framework will continue to be compatible with the codebase for any 0.9 point releases.

# Actual Results

The framework is no longer compatible with the codebase for any 0.9 point releases and requires changes for compatibility.

# Regression & Version

v0.9.8 vs v0.9.9

# Related Link

**Comment by weichsel** [comment]
ZIP Foundation is using Semantic Versioning.  

From the Semantic Versioning page you linked:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

The framework currently is still in its 0.9.x stage and will most likely stay there for some releases. 

Which API did break for you? I still tried to keep the API stable since the initial release and refrained from renaming symbols. All changes to method signatures where additional and optional.

**Comment by weichsel** [comment]
> when using an older version of Xcode (10.1) for Swift 4 binary based compatibility.

Since Swift does not have a stable Module format yet, binary frameworks are currently not possible. Even Swift 5 - which provides ABI stability - won't change that, because the `.swiftmodule` format remains subject to change.  

What dependency manager are you using to integrate ZIP Foundation?  
In my experience, the most flexible way to integrate 3rd party frameworks into a Swift project is via `carthage --no-build` (as described here: https://github.com/weichsel/ZIPFoundation#carthage)

> With the 0.9.9 version, it basically requires an Xcode update

ZIP Foundation currently supports Swift 4.0, 4.1, 4.2 & 5.0 and Xcode 10.0, 10.1 & 10.2.  
Our CI hosted on Azure Pipelines also uses Xcode 10.1 ATM.  
Maintaining source compatibility is - in contrast to binary compatibility - already possible with the Swift toolchain because we have a) directives for conditional compilation b) new compilers support compatibility modes for older language versions. So when using source dependencies, immediate Xcode updates should _not_ be necessary.
