### ISSUE TITLE
Cannot cancel extract operation

### ISSUE THREAD

**Issue by TheFlow95** [weichsel/ZIPFoundation#123]
I want to extract a file asynchronously so I used `OperationQueue` like this:
```swift
let queue = OperationQueue()
queue.addOperation {
    do {
        _ = try archive.extract(entry, to: temporaryFileURL)
        completionHandler(temporaryFileURL)
    } catch {
        print("Cannot extract video file: \(error)")
    }
}
```

And then I want to cancel my operation with `queue.cancelAllOperations()` but the extraction work doesn't stop…
How to fix it?

Thanks

**Comment by weichsel** [comment]
To cancel an extract operation, you have to pass in an instance of `Progress` and keep a reference to it so that you can call `cancel()` at a later point.  

You can find some details and a link to the `Progress` docs in the [progress tracking](https://github.com/weichsel/ZIPFoundation#progress-tracking-and-cancellation) section of the readme.
