### ISSUE TITLE
Help - Twice data size in archive?  

### ISSUE THREAD

**Issue by fblecha** [weichsel/ZIPFoundation#133]
I'm using the following:

```swift
    try? archive.addEntry(with: "myfile.xml",
                          type: .file,
                          uncompressedSize: UInt32(data.count),
                          compressionMethod: .none,
                          bufferSize: defaultWriteChunkSize,
                          progress: nil,
                          provider: { (position, size) -> Data in return data })
```
 and testing with unzip -t newArchive.zip gives me the following:

```bash
Archive:  newArchive.zip
myfile.xml:  ucsize 9449 <> csize 18899 for STORED entry
         continuing with "compressed" size value
    testing: myfile.xml        OK
At least one warning-error was detected in newArchive.zip.
```
the extracted myfile.xml looks ok with the exception that the file is written twice to the file (e.g. if I attempt to write the file "abcd", then myfile.xml contains "abcdabcd").  Also in the above, 9449 * 2 = 1898  (where's the extra byte from?)

## Observations:
1. It only seems to happen once I write a file that's of a large enough size (while I use "abcd" above, I'm writing files > 8K typically).  For a small enough file (a few key) it seems to work.  Maybe a buffer issue?

## Theories:
1. I'm calling it twice and appending - doesn't seem to be the case.  I put the above in a mutex and I'm only calling it once

2. I'm writing the data twice to the same entry.  Doesn't seem to be the case, as I checked writing the data (as a string) to a file and only had "abcd".

3. Something with using .utf8 encoding?

**Comment by weichsel** [comment]
Hi,

From the code snippet you provided, it looks like you are always returning the _full_ `data` object from your `Provider` closure. The main use case for the `Provider` based API is _chunk-wise_ writing. To provide chunks of `data`, you can use the `position` and `size` arguments that get passed into the closure. (Where `size` is either the buffer size, or - for the last call - the size of the final chunk).  

In hindsight I think I chose misleading parameters in the [`README`](https://github.com/weichsel/ZIPFoundation#closure-based-reading-and-writing) section for that API. 
I just created a PR (#134) that refines that, so that it better demonstrates that `provider` might be called multiple times. You can preview the new sample code [here](https://github.com/weichsel/ZIPFoundation/blob/eb55a304cc9b462c58a8ae31375b84983ce53b22/README.md#closure-based-reading-and-writing). 
Let me know if this helps in your case and sorry for the confusion.

**Comment by fblecha** [comment]
@weichsel that example totally helped.  In retrospect, it should have been something I thought of, but for some reason I thought the handling of buffer size and data subsets would be handled internally.  Thanks! 👍🏽
