### ISSUE TITLE
Can I use this in XCode 8.3.3 & Swift 3?

### ISSUE THREAD

**Issue by karishmapujara** [weichsel/ZIPFoundation#20]
Hello

Can I use this in XCode 8.3.3 & Swift 3?

**Comment by weichsel** [comment]
Hi,

There was already a pull request to introduce Xcode 8.x/Swift 3 compatibility. I had to close it because it broke the test suite and some aspects of the ZIP specification. 
If you want to make ZIPFoundation compatible with Xcode 8, you can have a look at this closed PR and my comments: https://github.com/weichsel/ZIPFoundation/pull/16

**Comment by karishmapujara** [comment]
OK
