### ISSUE TITLE
Tests in Xcode 12.4 run forever

### ISSUE THREAD

**Issue by valeriyvan** [weichsel/ZIPFoundation#207]
# Summary

Tests in Xcode 12.4 run forever

# Steps to Reproduce

Run tests in Xcode 12.4

# Expected Results

# Actual Results

# Regression & Version

# Related Link

**Comment by weichsel** [comment]
Is the test action in the scheme set to `DEBUG`? 
ZIPFoundation is way slower (order of magnitudes) when running unoptimized builds. The main bottleneck is the CRC32 calculation.  
The test suite does not run forever - it just takes very long to complete (because some test cases create quite large archives/entries).  
Please check the Build Configuration of the Test action in the Scheme Editor.
