### ISSUE TITLE
swift compiler error 

### ISSUE THREAD

**Issue by johnmci** [weichsel/ZIPFoundation#21]
while position < size {
            let readSize = (Int(size) - position) >= bufferSize ? Int(bufferSize) : (Int(size) - position)

swift compiler complains about comparing Int and UInt32 types. 

xCode 8.3.3. Swift LLVM 3.x

source/Mobile-iOS/Pods/ZIPFoundation/Sources/ZIPFoundation/Archive+Writing.swift:121:36: error: binary operator '>' cannot be applied to operands of type 'Int' and 'UInt32'
        if startOfCentralDirectory > UINT32_MAX {
           ~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~
source/Mobile-iOS/Pods/ZIPFoundation/Sources/ZIPFoundation/Archive+Writing.swift:121:36: note: overloads for '>' exist with these partially matching parameter lists: (UInt32, UInt32), (Int, Int)
        if startOfCentralDirectory > UINT32_MAX {

also 
if startOfCentralDirectory  > UINT32_MAX

**Comment by weichsel** [comment]
Hi,
ZIPFoundation targets Swift 4 (Which can be used for App Store apps since yesterday), but it should be possible to use it with older toolchains.
I recently had to close a pull request that fixed the compile issues with Swift 3.x but introduced some incompatibilities with the ZIP specification and the test suite. I added some comments to the relevant source locations: https://github.com/weichsel/ZIPFoundation/pull/16

**Comment by johnmci** [comment]
Thanks
