### ISSUE TITLE
Lower deployment target to 9.0

### ISSUE THREAD

**Issue by viktor-idenfy** [weichsel/ZIPFoundation#214]
Hello, as a developer of iDenfy company I would like to express my gratitude for this amazing library! After the latest update, we noticed that the minimal deployment target was increased to 12.0, which creates problems because we use this library inside of our SDK and deploy our SDK as a Cocoapods package. Many of the clients have a lower deployment target than 12.0.
 
Would you be open to reducing the deployment target to 9.0 as it was previously? You could still use if tags in Xcode to add specific functionality starting only the 12.0 version. Let me know, and thank you!

**Comment by weichsel** [comment]
Hi Viktor,

We intentionally raised the deployment target because the current Xcode version (12.4 at the time of writing) emits a build warning to raise the iOS deployment target when it does an upgrade check.  
Our CI is also no longer able to run the test suite on pre 12.0 iOS Simulators - so we can not perform any automated testing in that environment.
