### ISSUE TITLE
Update Entry in Archive

### ISSUE THREAD

**Issue by JoachimM7** [weichsel/ZIPFoundation#221]
It's possible to add and remove files to and from an `Archive`. But it's not possible to update a file. Of course I could remove the old one and add the changed one, but that will append the file to the end of the `Archive`. In the most cases this is not problematic, but for example for files like OpenDocument files the order of the files in the archive is important.

So I would suggest to add a func called `updateEntry` in the Archive.swift.

Some thoughts to that: I checked, how the `zip` cli is doing this. If you use `zip -u archive.zip changedFile`, then it really changes the file in the Archive. 
My suggestion: I think one could use the code from the func `remove` in `Archive+Writing.swift`. Then instead of skipping the removed item you can add the new entry. Unfortunately I do not completely understand the code here yet, otherwise I would make a pull request.

**Comment by weichsel** [comment]
Hi Joachim, 

ZIP files are organized as "sequence of files" with some interleaved metadata and a central directory structure (at the end of the file) that maintains additional metadata and offsets.  
When an entry gets removed, all subsequent entries have to be rewritten and the central directory must be updated to contain the new offsets. 
ZIP Foundation does that by [streaming all entries of an archive to a temp location](https://github.com/weichsel/ZIPFoundation/blob/8b01274e29d44a2989dc6855ec639c4df2b3b877/Sources/ZIPFoundation/Archive%2BWriting.swift#L170), skipping the entry that should be removed. After it reaches the end of the archive, it replaces the old archive with the new one. 
There might be slightly faster approaches that truncate the original file in-place and only rebuild the entries that are placed _after_ the removed entry - But our approach should be more secure on most file systems in the case that anything goes off the rails while rebuilding the tail entries.  

> My suggestion: I think one could use the code from the func remove in Archive+Writing.swift. Then instead of skipping the removed item you can add the new entry. Unfortunately I do not completely understand the code here yet, otherwise I would make a pull request.

I am not familiar with the OpenDocument format, but we are currently already have to balance performance and safety. Since the ZIP format specification does not make guarantees about entry order, I think it's better to handle that at the consuming side of the API.  

To implement that, you could look at the `remove` function linked above and instead of just skipping the removed entry, you could sneak-in the entry that you'd like to have at that location (You will also have to modify the code that does the book keeping of the offsets).

**Comment by JoachimM7** [comment]
Hi Thomas,

thank you for your answer. The OpenDocument standard says ([here](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part3.html#__RefHeading__752809_826425813)): `The “mimetype” file shall be the first file of the zip file. It shall not be compressed, and it shall not use an 'extra field' in its header.`

But this is only one background.... I just was wondering, why there is no function to update files (would be easier in the most cases then removing and adding and entry, especially because removing and adding both causes a complete rewrite of the file, does it?

**Comment by weichsel** [comment]
> The OpenDocument standard says (here): The “mimetype” file shall be the first file of the zip file. It shall not be compressed, and it shall not use an 'extra field' in its header.

Thanks for the link and for the background info.

> I just was wondering, why there is no function to update files
... 
> especially because removing and adding both causes a complete rewrite of the 

Consider you have the files ["A", "B", "C"] in an archive. If you replace "B" with a new file "D" (which could also be an updated version of "B"), you have to rebuild everything after "A" onwards because of size and offset changes. 
If "D" would have a smaller file size than "B", you could theoretically just overwrite parts of the former "B" but that would leave some remains of "B" in place. And you'd still have to update all metadata re. size. If "D" is larger than "B" you can't position the file pointer at the position of the former "B" and just write the contents of "D". In that case, you'd overwrite parts of "C" and corrupt the archive.   
So in terms of ZIP, there is no such thing as modify/update in-place.

**Comment by JoachimM7** [comment]
>  So in terms of ZIP, there is no such thing as modify/update in-place.

Of course, I know that (before using ZIPFoundation I started to create an own library for zip files, so I know sth. about the zip container). I'm absolutely aware, that you need to rewrite the file and change the offsets in the central directory. This is actually exactly what I am supposing, but I thought you may be faster adding such a function then me, because I don't completely understand your code yet ;)
