### ISSUE TITLE
Fail to unzip archive with european special characters

### ISSUE THREAD

**Issue by andreibudisan** [weichsel/ZIPFoundation#240]
# Summary
Backend returns a zip file as a response containing multiple files. The backend team assured me that the zip was archived using their library (apache commons-compress) in utf-8 encoding. I tried to use the library with all the encoding types defined in String.Encoding but none of them worked. 

Manually unarchiving the file (using the default macOS unzip functionality) works as expected.

# Steps to Reproduce
1. Download the sample zip file: [Samples.zip](https://github.com/weichsel/ZIPFoundation/files/7693350/Samples.zip)
2. Unarchive it using the `unzipItem` function

# Expected Results
Archive is unzipped as expected with all the files accounted for.

# Actual Results
Unzip process fails.

# Regression & Version
Tested on simulator: iPhone 13 Pro iOS 15.0
ZIPFoundation version: 0.9.14

# Related Link

**Comment by weichsel** [comment]
I was able to get the same results as the macOS Archive Utility by overriding the path encoding by providing `preferredEncoding: .utf8` to `unzipItem`.  

One thing I noticed is, that the entries do _not_ have the ZIP general purpose bit 11 set. This bit indicates the usage of UTF-8 for path encodings. If the path data actually _is_ encoded with UTF-8 and this bit is _not_ set, that's an error during archive creation.  
If you have control over the creation of the archive, you might be able to fix that there - otherwise, overriding the preferred encoding should work.

**Comment by andreibudisan** [comment]
Ok so i've tried to add the preferredEncoding option but with no success. Ironically it works without it but a file is missing: `Sample¡¿.pdf`. This is my test project code:

`   
    let fileManager = FileManager()
    fileManager.changeCurrentDirectoryPath(fileManager.temporaryDirectory.path)
    let currentWorkingPath = fileManager.currentDirectoryPath
    var sourceURL = URL(fileURLWithPath: currentWorkingPath)
    sourceURL.appendPathComponent("lyru2y.zip")
    let destinationURL = URL(fileURLWithPath: currentWorkingPath)
    do {
      try fileManager.unzipItem(at: sourceURL, to: destinationURL, skipCRC32: true)
    } catch {
      print("Extraction of ZIP archive failed with error:\(error)")
    }
`

Am I missing something?

**Comment by weichsel** [comment]
Thanks for providing the sample code.

> If i try to add preferredEncoding = .utf8 to the code i get:

The bytes stored in `Entry.CentralDirectoryStructure.fileNameData` of your archive are not a valid UTF8 sequences. When providing an explicit `preferredEncoding`, ZIPFoundation does _not_ throw when the path is not decodable with the given encoding. Instead it returns an empty string (this is not ideal and might change in the future) which leads to the confusing error message. 

> Sample¡¿.pdf is missing

It seems that the file is not missing, but that the path name is decoded differently. (Both sides in your screenshot show 20 entries. The left side has one file named `Sample¡¿.pdf` which seems to be named `Sampleí┐.pdf`.)  

There are 2 things you can try:
- The ZIP archiver that's used to create your archives seems to use the (inofficial "UTF-8 path name" subfield with the ID `0x7075`). ZIPFoundation does currently not support this particular field because its not part of the ZIP specification. You can fall back to extracting the archives manually instead of using the `FileManager.unzipItem()` convenience method (Check README.md for details). When iterating the archive, you can manually decode the path from `Entry.CentralDirectoryStructure.extraFieldData` instead of using `Entry.path`.

- Another option would be to find out what encoding the paths are actually using and use something like:
```swift
let dosRussian = 0x041B
let dosRussianEncoding = CFStringEncoding(dosRussian)
let dosRussianStringEncoding = CFStringConvertEncodingToNSStringEncoding(dosRussianEncoding)
let codepage866 = String.Encoding(rawValue: dosRussianStringEncoding)
```

for the `preferredEncoding`.
