### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by zkrige** [weichsel/ZIPFoundation#29]
`archive[filename]` isn't thread-safe. If you call this multiple concurrent times from threads, the list of entries is corrupted. I had to wrap my code in objc @synchronized to make it work.

`archive.extract` also isnt threadsafe, and if it is invoked from multiple threads concurrently, it corrupts the output files

**Comment by weichsel** [comment]
ZIP Foundation does not ensure thread safety at any level by design.
The `Archive` class maintains the state of its underlying file descriptor for performance reasons and is therefore not re-entrant.  
But you can achieve concurrent extraction of entries by creating multiple instances of archives from the same source URL (Instantiating `Archive` is lightweight as it only builds the internal entry index and opens a file descriptor in its `init`): 

```swift
let entryPaths = originalArchive.map { $0.path }
guard let firstArchive = Archive(url: archiveURL, accessMode: .read) else { return }
guard let secondArchive = Archive(url: archiveURL, accessMode: .read) else { return }

// Assuming an even number of entries here
let firstBatchOfPaths = entryPaths[0..<entryPaths.count/2]
let secondBatchOfPaths = entryPaths[entryPaths.count/2..<entryPaths.count]

let firstQueue = DispatchQueue(label: "first")
firstQueue.async {
    for path in firstBatchOfPaths {
        guard let entry = firstArchive[path] else { continue }
        _ = try? firstArchive.extract(entry, consumer: { print("extracted: \($0.count) on queue:\(firstQueue.label)") })
    }
}

let secondQueue = DispatchQueue(label: "second")
secondQueue.async {
    for path in secondBatchOfPaths {
        guard let entry = secondArchive[path] else { continue }
        _ = try? secondArchive.extract(entry, consumer: { print("extracted: \($0.count) on queue:\(secondQueue.label)") })
    }
}
```
The above approach can be used for any number of queues as long as you are only performing `read` operations.

**Comment by zkrige** [comment]
brilliant. thank you so much for the detailed advice and example

**Comment by weichsel** [comment]
You are welcome!
