### ISSUE TITLE
Compiler error: some methods is only available on OS X 10.11 or newer

### ISSUE THREAD

**Issue by AlanMcKen** [weichsel/ZIPFoundation#30]
MacOS: **10.12.6**
Swift: **4.0**
Xcode: **9.0.1**

Hi,
 
during compilation, Xcode issues compatibility errors:

```'compression_stream_init' is only available on OS X 10.11 or newer```

```'compression_stream_destroy' is only available on OS X 10.11 or newer```

```'compression_stream_process' is only available on OS X 10.11 or newer```

in 
```swift
process(operation:size:bufferSize:provider:consumer:)
``` 
To resolve this issues Xcode proposes to add ```@available (OSX 10.11, *)``` to enclosing methods or extensions.

**Comment by weichsel** [comment]
I assume you integrated ZIP Foundation via Swift Package Manager. The SPM does default the deployment target to macOS 10.10. ZIP Foundation requires at least 10.11 because the API you mentioned is not available in prior versions.
Last time I checked, the SPM package format did not offer any flags to define the minimum deployment target so you'll have to manually configure the "Deployment Target" setting in your Xcode project.

If you are building from the command line, this blog post describes a workaround:
https://oleb.net/blog/2017/04/swift-3-1-package-manager-deployment-target/

**Comment by AlanMcKen** [comment]
You're right, setting the Deployment Target manually resolves the issue. Thank you! It remains to wait while SPM will support build settings...

**Comment by krzyzanowskim** [comment]
I'll chip in. I think the project is great, though the SPM issue hit me today too. It's fairly easy to build `CZlib` only version with SPM. The SPM uses `SWIFT_PACKAGE` flag for the autogenerated Xcode project. With this flag on the project could build the "Linux" version.

Anyways, I forked to use `CZlib` on all platforms.
`.package(url: "https://github.com/krzyzanowskim/ZIPFoundation.git", .branch("CZlib"))`

**Comment by weichsel** [comment]
I am really sorry for that mess with the deployment target. Hopefully Apple addresses this soon in SPM. 

I saw that you also fixed a build error on Linux in your fork. I recently submitted a PR that adds the missing convenience method to Swift Foundation: https://github.com/apple/swift-corelibs-foundation/pull/1420 .

**Comment by krzyzanowskim** [comment]
yea, I filled a bug report too https://bugs.swift.org/browse/SR-6924 haha
