### ISSUE TITLE
Default compression method in Archive.addEntry should be .deflate

### ISSUE THREAD

**Issue by cwimberger** [weichsel/ZIPFoundation#43]
First and foremost, thanks for this great library! It is clean and really easy to integrate.

However, our created zip files are much bigger than the ones created by e.g. OS X. After a bit of investigation, I've discovered that the default compression method of `Archive.addEntry` is `.none` and I wonder if this is a good choice. 

Is there a reason for that? It could be that other people don't check the file size and their applications never really compress the created zip files.

**Comment by weichsel** [comment]
> First and foremost, thanks for this great library! It is clean and really easy to integrate.

Thank you, Christoph!

The main reason why I chose`.none` as the default is because the File Format Specification describes ZIP as a file storage format with _optional_ support for compression. 
From the [specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT):

> 4.1.3 Data compression MAY be used to reduce the size of files
>    placed into a ZIP file, but is not required. 

Your point, that most people will expect compression when creating ZIP archives is certainly true. 
But on the other hand, uncompressed archives are also a good choice for common use cases. (Whenever speed over file size is preferred. e.g. when using ZIP as container format for document packages.)

**Comment by cwimberger** [comment]
I've never seen a zip command line tool that uses no compression as a default. Maybe that is why I assumed that compression is enabled by default. 

But you are right, it is certainly a debatable question what the best default value here is.

(Feel free to close this issue.)

**Comment by levigroker** [comment]
I agree with @cwimberger, and I submit that deflate should be the default behavior.

From the specification: "ZIP is one of the most widely used compressed file formats." and "Compression method 8 (Deflate) is the method used by default by most 
   ZIP compatible application programs." which both indicate to me the specification also considers compressed content to be the default behavior.

While I agree ZIP is a container format and has legitimate use cases as an uncompressed container, I would suggest this is not the generally expected default behavior.
