### ISSUE TITLE
Issue with Read-Only Directory inside Zip File

### ISSUE THREAD

**Issue by winsmith** [weichsel/ZIPFoundation#52]
# Summary
A zip file I'm trying to unpack has a root level directory, which has write and executable bits set to false. This causes the unpack process to fail, because the process cannot write into the directory it has just created.

The solution I'd like to suggest is to manually set the `rwx` bits on all directories created during extraction.

# Steps to Reproduce
1. Download  https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip
2. Unpack using the following code:

```swift
let workingDirectory = URL.init(fileURLWithPath: "/Users/yourname/zipfoundation_temp")
let sourceUrl = workingDirectory.appendingPathComponent(zipFileName)
let destinationUrl = workingDirectory

do {
    try fileManager.unzipItem(at: sourceUrl, to: destinationUrl)
} catch {
    print("Extraction of ZIP archive failed with error:\(error)")
}
```

# Expected Results
The ZIP file is extracted.

# Actual Results
The extraction fails with the following error: 

`Extraction of ZIP archive failed with error:Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “10kmOmniEVA4RT” in the folder “CKAN-meta-master”." UserInfo={NSFilePath=/Applications/Kerbal Space Program/temp/CKAN-meta-master/10kmOmniEVA4RT, NSUnderlyingError=0x600000851e50 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}`

# Submitter's Note
Thanks for the excellent docs to this library :)

**Comment by winsmith** [comment]
Edited to add: If you gave me a few pointers where in the codebase I should add this functionality, I could totally create a pull request for this if you'd like.

**Comment by weichsel** [comment]
Thank you for filing this detailed issue. This is clearly a bug and should be addressed.   

It'd be awesome if you can contribute a PR to fix this.  
I think the best location would be the `unzipItem:` method of the `FileManager+ZIP` extension.  

Some things to consider when dealing with directory entries within ZIP Archives:
 - ZIP does not require explicit directory entries. `.file` entries that are stored with a nested `path`, implicitly create their parent directories during extraction.
 - `.file` and `.directory` entries must be extracted before `.symlink` entries because otherwise creating the symlink on the file system fails.

The following approach could work to avoid creation of readonly directories _before_ `.file` entry extraction:  
1. Bring entries into the following order `.file`, `.directory`, `.symlink`
1. Perform `.file` extraction
1. During `.directory` extraction, deal with exceptions that indicate that the directory has already been created. In that case, just apply `Entry.fileAttributes` to the existing directory.
1. Perform symlink extraction.

**Comment by winsmith** [comment]
Cool, thanks for the help! I'll try to file a PR this week. 😊

**Comment by winsmith** [comment]
I've dived into this a bit and it turns out, the error occurs because ZIPFoundation sets 644 as default permissions for directories. It has nothing to do with the permissions inside my specific zip file; like any other zip file generated by Github's "Download archive" feature, it contains no file permission information. 

When ZIPFoundation was unpacking the file, it set both files and directories' permissions to `644`, which causes `FileManager` to throw "Permission Denied" errors when trying to write into them, as their [directory executable bit](https://unix.stackexchange.com/questions/21251/execute-vs-read-bit-how-do-directory-permissions-in-linux-work) is not set.

I'm preparing a PR now that introduces a separate default permission set for directories.

**Comment by StackHelp** [comment]
@winsmith how to solve this?
