### ISSUE TITLE
Fatal Error: NSFileModificationDate not implemented when unzip item on Linux.

### ISSUE THREAD

**Issue by IsaacXen** [weichsel/ZIPFoundation#65]
# Summary

Fatal error when tried to unzip on linux.
Same code, everything works well on macOS, but failed on linux.

# Steps to Reproduce

```
try FileManager.default.unzipItem(at: urlToZip, to: urlToDest)
```

I make a small demo to reproduce this:

```
git clone https://gitlab.com/isaacxen/zipFoundationErrorDemo.git
cd zipFoundationErrorDemo/
cp example.epub /tmp
swift package update
swift run
```

# Expected Results

successfully unzip.

# Actual Results

```
Fatal error: Attribute type not implemented: FileAttributeKey(rawValue: "NSFileModificationDate"): file Foundation/FileManager.swift, line 139
```

# Regression & Version

ZipFoundation: 0.9.6
Ubuntu 16.04
Swift 4.1

# Related Link

**Comment by weichsel** [comment]
I was able to reproduce the issue with your test repository. Thanks for taking the effort to write a quick sample - this really helps.

The problem is, that [Swift's corelibs Foundation](https://github.com/apple/swift-corelibs-foundation) (which is used on Linux as replacement for the closed source Foundation on iOS/macOS/...) lacks file modification date support in `FileManager`.

I plan to submit a patch to corelibs Foundation soon.  
In the meantime you can extract your archive with ZIPFoundation by using the `Archive` class directly (instead of the `FileManager.unzipItem()` method.  
You can iterate over all entries in an archive via:

```for entry in archive```

More information can be found in the [README](https://github.com/weichsel/ZIPFoundation#accessing-individual-entries).

**Comment by TheVanDoom** [comment]
Is there any way to extract the archive on Linux now? Iterating over the archive is nice and all, but the execution fails when calling the extract-method of the archive. Or is there another way to get the extracted result from the entry than calling `archive.extract(...)` ?

**Comment by weichsel** [comment]
Extracting via `Archive` should work on Linux. Only the `FileManager` extension cannot be used because corelibs Foundation still has no implementation for the file modification date attribute.  

If you can provide some details about your environment (Swift Version, Linux distribution, ...) and a source snippet of your extraction code I can have a look.

**Comment by TheVanDoom** [comment]
The application is build with Swift 4.2.1 and runs in a docker-container with Ubuntu 18.04. I use the following code to extract the archive:

`
...
guard let archive = Archive(url: zipURL, accessMode: .read) else  {
    return
}
archive.forEach {
    try archive.extract(entry, to: workDir. appendPathComponent($0.path))
}
...
`

**Comment by weichsel** [comment]
What `Error` do you get?

**Comment by TheVanDoom** [comment]
The same as stated in this issue.
`Fatal error: Attribute type not implemented: FileAttributeKey(rawValue: "NSFileModificationDate"): file Foundation/FileManager.swift, line 139`

**Comment by weichsel** [comment]
I just wrote a small test program to check the current state of Linux support.  

My original statement, that only the `FileManager` based extraction is affected by the missing `modificationDate` support is wrong. My mistake - Sorry for the confusion.  
`Archive.extract(_ entry, to url)` also tries to set the modification date and therefore fails on Linux. (I will update my first response in this issue to make this clearer).  

However, there is a second `Archive.extract` method, that takes a `consumer` closure. This method does not create the destination file and therefore does not set the `Entry` file attribute. This one can be used on Linux but you have to create the destination file yourself and append the `data` passed into the `consumer` closure.

**Comment by TheVanDoom** [comment]
Ok, thank you very much. I'll give that a try.

**Comment by weichsel** [comment]
I updated my first reply with some details on how to work around this issue.
