### ISSUE TITLE
Initialize Archive from a Data instance

### ISSUE THREAD

**Issue by florianreinhart** [weichsel/ZIPFoundation#70]
I need to download a zip file and extract one file into memory for further processing. I get the zip file as a `Data` instance from NSURLSession. It would be great to instantiate an `Archive` without writing the `Data` to disk first (which is what I currently do to work around this).

**Comment by weichsel** [comment]
Hello Florian,

ZIP files have their archive index (the central directory) at the end of the file. An initialiser that accepts a `Data` argument would therefore require the whole archive to be in memory so that it can parse the ZIP central directory. A design like that would be an incentive for API users to pass around large archives as `Data` instances instead of using the built-in, chunk based reader.   
While the latter requires archives to be backed by a file, it guarantees predictable memory consumption.

**Comment by florianreinhart** [comment]
I agree that in general it is a bad idea to hold a ZIP archive in memory, especially on mobile devices. And also the API should absolutely not encourage such usage.

However, let me explain my use case in detail. I am running this on a Linux server and memory is not an issue. I download a ZIP file from a third party API every minute using `(NS)URLSession`. This ZIP file is just a few MBs large and only contains one XML file. I extract the XML into a `Data` instance and then feed it into `(NS)XMLDocument`. So for me it unnecessary to write the downloaded ZIP to disk, I already have in memory.

Maybe we can come up with an API that makes this possible, but does not encourage it. Do you have any ideas?

**Comment by weichsel** [comment]
Hmmm, maybe you can make use of tempfs on Linux?  
This way you can just write into an in-memory file and forward the URL to that file to ZIP Foundation.  
That way the internals of the framework can perform the usual POSIX file API calls but your data will never hit the physical disk.

**Comment by florianreinhart** [comment]
That's a good idea!

Since I am already using Docker with docker-compose, I created a volume using tmpfs in the service definition:

```yaml
volumes:
  - type: "tmpfs"
    target: "/tmp"
    tmpfs:
      size: 100000000 # 100MB
```

I'd still prefer a solution in the ZIPFoundation API, but this works for me.

**Comment by weichsel** [comment]
At least a workaround :)
I will think about an in-memory only initializer - maybe this becomes a common request.  

Thank you for your input!
