### ISSUE TITLE
Vulnerability of traversal attack

### ISSUE THREAD

**Issue by waynezhang** [weichsel/ZIPFoundation#74]
# Summary
ZIPFoundation could be attacted by archive traversal attack[1]

# Steps to Reproduce
1. Put `evil.zip`[2] attached to somewhere (directory A)
2. Unzip `evil.zip` using ZIPFoundation to another place (directory B).

# Expected Results
`evilfile` is extracted in directory B (or failed maybe)

# Actual Results
`evilfile` will be extracted in the parent directory of `evil.zip` (parent of directory A)

# Regression & Version
`0.9.6`

# Related Link
[1] https://en.wikipedia.org/wiki/Directory_traversal_attack#Zip/archive_traversal_attacks
[2] [evil.zip](https://github.com/weichsel/ZIPFoundation/files/2248247/evil.zip)

**Comment by weichsel** [comment]
Thank you for pointing out this issue (and sorry for the delayed reply).  

I will try to fix the problem with the next release, but I don't know yet when I will find time to work on ZIP Foundation.   
I'd also be happy to review and merge a fix if you can contribute a pull request.

**Comment by brduffy** [comment]
I'm new to using the zip file format. Is there a way for me to check in my own Swift code to make sure zip foundation is not extracting files to a place where I don't want them or is that something I need to wait for a fix for in zipfoundation itself?

**Comment by weichsel** [comment]
@brduffy If you are using ZIPFoundation on Apple platforms with a sandboxed environment (iOS, macOS, ...), there shouldn't be a problem because ZIP entries with paths _above_ the root will fail to extract. Just make sure you are handling write errors properly.  

In non-sandboxed environments, you can add a pre-process step by iterating over all entries and check if their paths are trying to escape the root of your destination URL.  

I will add code that performs that check in the next release. If you find time to submit a pull request, I can also review and merge your solution.

**Comment by pwntester** [comment]
Have fixed a similar library with something like:

```
NSString *fullName = [NSString stringWithFormat:@"%@/%@", destPath, entry.name];
NSString* normalizedName = [fullName stringByStandardizingPath];
if ([normalizedName hasPrefix:destPath]) {
       // extract
} else {
       // fail
}
```

**Comment by weichsel** [comment]
@pwntester Looks good - Thank you. If you can spare some time, It'd be great if you can open a pull request with your fix. (Maybe you can use to the more Swift-like [`URL.standardizedFileURL()`](https://developer.apple.com/documentation/foundation/url/2293229-standardizedfileurl). 
Otherwise I will add your code the next time I work on the project.
