### ISSUE TITLE
Missing tag for version 0.9.7

### ISSUE THREAD

**Issue by MattiasBowallius** [weichsel/ZIPFoundation#89]
Hi!

It seem like you have missed to push the tag for version 0.9.7.

//Mattias Bowallius

**Comment by weichsel** [comment]
Hi Mattias,

ZIP Foundation 0.9.7 shipped with a bug that prevented extraction to symlinked destination directories.  Of course I discovered this shortly _after_ hitting release.  To prevent propagation of the faulty version, I temporarily removed the tag.

I now re-tagged the bad 0.9.7 release but additionally published a fixed version 0.9.8 so that people that update now, can go straight to the fixed version.

Sorry for the inconvenience.
